### ISSUE TITLE
checklist on query methods in Axon endpoint

### ISSUE THREAD

**Issue by fjchen7** [synapseweb3/relayer#164]
Due to [AXON IBC implementation](https://github.com/synapseweb3/ibc-solidity-contract/) or undetermined encoding, there are some issues on query methods should be tracked and wait for later fix.

**Not support**
- [x] `query_balance`
- [ ] `query_all_balances`
- [x] `query_denom_trace`
- [x] `query_commitment_prefix`
- [x] `query_application_status`
- [x] `query_upgraded_client_state`: not involved in main flow.
- [x] `query_upgraded_consensus_state`: not involved in main flow.
- [x] `query_txs`
- [x] `query_packet_events`
- [x] `query_host_consensus_state`
  https://github.com/synapseweb3/forcerelay/pull/365

**Not support fetch for proof**
- [x] `query_client_state`
- [x] `query_consensus_state`
- [x] `query_connection`
- [x] `query_connections`
- [x] `query_channel`
- [x] `query_packet_commitment`
- [x] `query_packet_acknowledgement`
- [x] `query_next_sequence_receive`

**Uncertain implementations**
- [x] `query_packet_receipt`: what should be returned for bytes in response?
- [x] `query_packet_acknowledgements` and `query_unreceived_acknowledgements`: what sequences should be returned?

## Related PRs
- https://github.com/synapseweb3/forcerelay/pull/347

**Comment by ashuralyk** [comment]
not all of above methods should be implemented

**Comment by jjyr** [comment]
I have implemented the QueryHeight in this PR https://github.com/synapseweb3/forcerelay/pull/347

**Comment by jjyr** [comment]
记录下关于 DenomTrace 的实现

这里解释了要实现的原因，在 token 经过多次 hops 后 cosmos SDK 会 hash denom full path, 所以需要支持从 hash 查找 

https://github.com/cosmos/cosmjs/issues/756

已有的可以参考的实现方式是在 PacketRecv 时查找 denom 并且存储到 store 中

https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/relay.go#L259

考虑到简化实现，我们可以直接存储到合约中。 cc @blckngm

**Comment by blckngm** [comment]
现在实现下 ICS20TransferERC20 为收到的 denom 部署的 ERC20 tokens 的 name 是 IBC/hash(denom), 可以把反向的 mapping 也存一下 (name -> full denom) 就行？

**Comment by blckngm** [comment]
哦，看起来 ibc-go 的 transfer 还支持直接用 ibc/hash 这样的 denom 来 transfer, 这个我们也可以考虑支持。

**Comment by blckngm** [comment]
Event 也还是可以加一下

**Comment by jjyr** [comment]
这块其他的我不太清楚具体需求，我会先开始做 denomTrace 这一小块，先支持未实现的接口。

是的，只要存下来反向 mapping 就行，那就不用在 packet recv 里做了。
