### ISSUE TITLE
merge latest version of Hermes framework after finishing Forcerelay/Axon

### ISSUE THREAD

**Issue by ashuralyk** [synapseweb3/relayer#255]
## Tasks

- [ ] https://github.com/informalsystems/hermes/releases

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
