### ISSUE TITLE
checklist on pushing Ckb endpoint from connection/channel to packet

### ISSUE THREAD

**Issue by ashuralyk** [synapseweb3/relayer#265]
features:
- [x] support SDK of listening, assembling and sending further packet cells and transactions
- [ ] #343

optimization (optional):
- [x] erase useless fields from packet and channel args and optimize for the easy search of ckb-indexer
- [x] treat port id as the hash of user's lock script

**Comment by ashuralyk** [comment]
@blckngm any concerns can be posted here, I've added the concern of index usage in the checklist

**Comment by blckngm** [comment]
Some checks are missing for SendPacket/WriteAck:

* SendPacket destination channel/port (https://github.com/synapseweb3/ckb-ics/pull/15).
* WriteAck new channel status (https://github.com/synapseweb3/ckb-ics/pull/14).
* ~~WriteAck sequence for ordered channels~~ (Edit: next_sequence_acks is for recvPacket).

**Comment by blckngm** [comment]
* There are some per-defined cell capacities in ckb-ics-axon but they are not enforced in the contracts. (Edit: this should probably be checked in the “type id” script.)

**Comment by ashuralyk** [comment]
> * There are some per-defined cell capacities in ckb-ics-axon but they are not enforced in the contracts.

this is fixed in the latest commit of PR:
- https://github.com/synapseweb3/forcerelay/pull/305

**Comment by Flouse** [comment]
> * There are some per-defined cell capacities in ckb-ics-axon but they are not enforced in the contracts. (Edit: this should probably be checked in the “type id” script.)

- tracked in https://github.com/synapseweb3/forcerelay/issues/326
  to be discussed
